### ISSUE TITLE
Contribution: Ultra high quality THX IRs Preset

### ISSUE THREAD

**Issue by lexterror** [timschneeb/RootlessJamesDSP#208]
Hi,

I wanted to contribute this 24bit wav IRS preset.

Its 6MB in size

The software I used is:

-Windows 11 OS
-https://wavearts.com/products/plugins/mlstool
-THX Spatial Creator (Concert Hall Preset)
-VSTHost
-Virtual Audio Cable

Please let me know if its of use...

Thank you!

[THXIRMAX_ConcertHall.zip](https://github.com/ThePBone/RootlessJamesDSP/files/14487047/THXIRMAX_ConcertHall.zip)

**Comment by BRBsoup** [comment]
> Hi,
> 
> I wanted to contribute this 24bit wav IRS preset.
> 
> Its 6MB in size
> 
> The software I used is:
> 
> -Windows 11 OS -https://wavearts.com/products/plugins/mlstool -THX Spatial Creator (Concert Hall Preset) -VSTHost -Virtual Audio Cable
> 
> Please let me know if its of use...
> 
> Thank you!
> 
> [THXIRMAX_ConcertHall.zip](https://github.com/ThePBone/RootlessJamesDSP/files/14487047/THXIRMAX_ConcertHall.zip)

Hey thanks for sharing. This file should be unzipped and imported under the "Convolver" setting, and compare it with the default Church setting - its very nice :) thanks again!

**Comment by timschneeb** [comment]
Hi, thanks for sharing your IR files.

I can't bundle any other IR files in the app because they are too big and would inflate the APK size too much. 
Because of that, I'm only bundling James' three IR files with the app.

But you can also share the files in the official JDSP telegram group if you like: https://t.me/jDSP_V4A
